### ISSUE TITLE
Utilisation des fonctions dans les ComparatorExpression 

### ISSUE THREAD

**Issue by HAJBIR** [oneteme/jquery#13]
ComparatorExpression : LENGTH.of => LESSTHAN

**Comment by usfalami** [comment]
Tu peux résoudre le problème :
1. créer une nouvelle column LENGTH_$COLUMN1
2. créer l'expression relative (new_expression)  => lessThan($value) 
3. Usage : LENGTH_$COLUMN1= new_expression

**Comment by usfalami** [comment]
Corrigé sur la v3, vous pouvais désormais appliquer la fonction sur la column directement dans l'URL : column.length.le=value
