### ISSUE TITLE
Ajouter les valeurs des parametres des requetes SQL dans la log

### ISSUE THREAD

**Issue by thtran1** [oneteme/jquery#28]
Dans la log serveur, nous avons les requêtes SQL générés par JQuery, peut-on avoir aussi les valeurs des paramètres de ces requêtes.
Ce qui évitera de regarder le paramétrage de jquery.

**Comment by usfalami** [comment]
Si vous utilisez JQuery pour exécuter les requêtes (log=DEBUG), les paramètres seront bien tracer dans la LOG.
En revanche si vous utiliser un autre framework (ex: spring JDBC) il faut configurer le bon level (org.springframework.jdbc.core = TRACE) pour tracer les paramètres

**Comment by usfalami** [comment]
Si vous utilisez JQuery pour exécuter les requêtes (log=DEBUG), les paramètres seront bien tracer dans la LOG.
En revanche si vous utiliser un autre framework (ex: spring JDBC) il faut configurer le bon level (org.springframework.jdbc.core = TRACE) pour tracer les paramètres
